/* readline.vapi generated by valac 0.56.0, do not modify. */

[CCode (cheader_filename = "fake_readline.h")]
public delegate string d_readline (string prompt);
[CCode (cheader_filename = "fake_readline.h")]
public static string readline (string prompt);
